### ISSUE TITLE
关于文档

### ISSUE THREAD

**Issue by Innei** [mx-space/kami#108]
这个项目是根据我个人的需要又或者是为了好玩而建立的，最初的目的是摆脱 typecho 的束缚。所以我就直接写了一个类似博客。如今断断续续开发维护了3 个多月，我在想着要不要写个文档。如果大家想尝试或者感兴趣的话，可以在下面留言，我看情况写文档和用户引导。

一是因为，如果没人想用的话，我写文档和画用户引导的页面有点划不来。二是因为这个月和下个月我可能会比较忙。在学习方面和工作方面，可能兼顾需要花大量时间。难得的时候要需要时间休息放松。

**Comment by ADD-SP** [comment]
希望可以有一个文档，对主题很感兴趣。

**Comment by Innei** [comment]
现在主要是后台管理那边写的太烂了，想用vue3重构。

**Comment by ADD-SP** [comment]
> 现在主要是后台管理那边写的太烂了，想用vue3重构。

时不时来催更（

**Comment by Katou-Kouseki** [comment]
加油 期待一下

**Comment by kfyidrig** [comment]
必须要啊，我小白，不会部署，谢谢大佬咯

**Comment by Innei** [comment]
满 100 Star 写文档
