### ISSUE TITLE
友情链接author must be a string问题

### ISSUE THREAD

**Issue by MoeCinnamo** [mx-space/kami#1297]
有的时候提交友情链接，会显示author must be a string。

**Comment by ttimochan** [comment]
> 有的时候提交友情链接，会显示author must be a string。

请问你的kami版本是最新版么？

**Comment by ttimochan** [comment]
最新版kami未能复现该问题

**Comment by MoeCinnamo** [comment]
> 最新版kami未能复现该问题

不知道，我申请友链 https://blog.iucky.cn/ 就出现了这个问题。

**Comment by ttimochan** [comment]
> > 最新版kami未能复现该问题
> 
> 不知道，我申请友链 https://blog.iucky.cn/ 就出现了这个问题。

他不是最新版本的kami，我将会关闭这个issue

**Comment by ttimochan** [comment]
该BUG已经在较新版本修复
