### ISSUE TITLE
一些小小的个人想法

### ISSUE THREAD

**Issue by yuano0** [mx-space/kami#1492]
### Clear and concise description of the problem

清晰简洁的问题描述

用Kami也挺久了，就我使用的来说说，kami真的很好啊，而且一些维护的人也非常友善，有问必答，超级喜欢这个的。

想来说一下一些自己的想法。

1：个人理解，<近期技术输出-用文字记录生活> 是可以用来记录技术和生活输出的，

诉の动态是可以用来写一些生活中的一些小事情的，感觉诉会让我用的更习惯一点。

但是我在想诉的时候，说一些琐碎的小事等等，其实我是希望诉可以有些互动的，诉它没有评论功能，会让我稍微苦恼点。。

2：评论功能

感觉评论的表情好单调噢，是一些颜文字，或许会不会加一些emoji等等表情包能更好玩一些......

这只是我的一些想法，或许可以做一个点子，

### Suggested solution

评论和诉。 

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by wibus-wee** [comment]
评论的表情包理论来说是可以做成自定义的，不知道 innei 的想法是什么

兴许可以让他们自己载入一个外部的 json or 在 config 里写，在加载页面后就载入它，那这样就可以达到很大的自定义程度了

**Comment by wibus-wee** [comment]
关于诉的评论的问题的话.. 应该是给 comment model 加上这个的支持就好，要不然就做一个跟 Github 类似的伪评论

不过这一切都需要问问  innei 的意见如何～

非常感谢你的意见

**Comment by Innei** [comment]
@wibus-wee 就等你 PR 了，大佬

**Comment by Innei** [comment]
> 大佬有考虑过加个书单的功能嘛，跟番剧一样那种，感觉看一些书记录下来也挺有意义的😶

海报墙，书单，游戏墙 其实还可以做很多

**Comment by Innei** [comment]
Closed, Not Plan
