### ISSUE TITLE
华为手机评论区全黑问题

### ISSUE THREAD

**Issue by yuano0** [mx-space/kami#1548]
操作信息：
操作系统 Ubuntu / 20.04 LTS amd64 (64bit) 
面板版本 3.26.4
系统版本 3.41.0

问题手机：华为手机
浏览器：华为手机自带浏览器
![Screenshot_20230120_134445_com huawei browser](https://user-images.githubusercontent.com/106160716/213722051-ab7a86f2-012e-44b8-9f94-55d8c53a90df.jpg)
![Screenshot_20230120_134505_com huawei browser](https://user-images.githubusercontent.com/106160716/213722064-ca8a93f8-ab43-42d2-95d9-5c61285d935c.jpg)

网站用户反馈，华为手机自带浏览器，评论区会出现bug，

**Comment by wibus-wee** [comment]
华为自带浏览器内核老旧，不考虑兼容

**Comment by miaoermua** [comment]
小米浏览器可能出现卡开场绿幕 logo，华为浏览器能看就不错了，小米机型目前通过 play 商店更新 webview 即可解决，系浏览器内核版本过低

建议换 Edge 或者 Chrome 或 Safari浏览器
内核版本至少 90 以上

如果没有其他信息补充一个星期内将关闭 issues

**Comment by miaoermua** [comment]
手机可以使用 Edge 浏览器或者 Chrome

**Comment by ttimochan** [comment]
浏览器内核版本过低，至少得 Chrome 94

**Comment by wibus-wee** [comment]
这浏览器我才发现没更新（）
这问题...
