### ISSUE TITLE
文档中一键脚本和预设脚本caddy反代存在问题

### ISSUE THREAD

**Issue by Sayyiku** [mx-space/kami#1551]
### 相关版本
![image](https://user-images.githubusercontent.com/77047823/214076389-b3dd3027-720c-43d6-8067-d9347c1a4626.png)

### bug展示
![image](https://user-images.githubusercontent.com/77047823/214076519-8c809518-15cb-4767-8f2d-8157964dd9a7.png)
![)4$KFZ )R T6GXZ%1$GB9 G](https://user-images.githubusercontent.com/77047823/214077121-c19277e0-955b-4a5c-8814-b19aaa49740a.png)

### 服务器采用的ubuntu20,部署方式根据了 使用预设脚本部署，访问  域名/proxy/qaqdmin ，进行初始化
![image](https://user-images.githubusercontent.com/77047823/214077406-a7019695-5ff6-42ac-a451-74dff90629c1.png)

### Reproduction

Reproduction

### System Info

```Shell
root@clean-path-1:~/mx-space/docker# npx envinfo --system --binaries --browsers
Need to install the following packages:
  envinfo@7.8.1
Ok to proceed? (y) y

  System:
    OS: Linux 5.4 Ubuntu 20.04 LTS (Focal Fossa)
    CPU: (2) x64 QEMU Virtual CPU version (cpu64-rhel6)
    Memory: 1.03 GB / 1.96 GB
    Container: Yes
    Shell: 5.0.16 - /bin/bash
  Binaries:
    Node: 16.19.0 - ~/.nvm/versions/node/v16.19.0/bin/node
    npm: 8.19.3 - ~/.nvm/versions/node/v16.19.0/bin/npm
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by ttimochan** [comment]
请详细描述一下你使用预设脚本的操作。（作为文档的维护者，我并未验证过脚本的实际可用性）

**Comment by Sayyiku** [comment]
无任何其他操作，全程按照预制脚本操作，各项环境也皆符合，值得一提的是，一键脚本方案部署也存在同样的问题。

**Comment by ttimochan** [comment]
> 无任何其他操作，全程按照预制脚本操

已经收到，请暂时选择手动安装，我会在近期修复脚本

**Comment by Innei** [comment]
@Sayyiku 请提供复现地址

**Comment by Sayyiku** [comment]
@Innei catcat.blog 环境皆为上述描述，vps也是新开的，不存在与其他项目冲突可能

**Comment by Innei** [comment]
<img width="505" alt="image" src="https://user-images.githubusercontent.com/41265413/214552792-651ed3e6-9840-409c-a568-b56f1f9acec0.png">
@Sayyiku 你是不是还没初始化。我看数据没有用户

**Comment by Sayyiku** [comment]
## 访问/proxy/qaqdmin进行初始化显示

![image](https://user-images.githubusercontent.com/77047823/214553573-15f7b0a1-5fd0-4999-bbfe-ee352dd13888.png)

{"ok":0,"message":"Cannot GET /"}

还是你指的/src/app.config.ts这个文件下添加自己的域名？

**Comment by Innei** [comment]
> ## 访问/proxy/qaqdmin进行初始化显示
> ![image](https://user-images.githubusercontent.com/77047823/214553573-15f7b0a1-5fd0-4999-bbfe-ee352dd13888.png)
> 
> {"ok":0,"message":"Cannot GET /"}
> 
> 还是你指的/src/app.config.ts这个文件下添加自己的域名？

看上去反代不太对哦

**Comment by Sayyiku** [comment]
那应该文档中 一键脚本 和 预设脚本 存在问题,我本地部署是可以的

**Comment by Innei** [comment]
不清楚你的配置。/proxy/qaqdmin 打到了 / 这是不对的

**Comment by Sayyiku** [comment]
> /proxy/qaqdmin

什么是 / 这是不对的?

**Comment by ttimochan** [comment]
> > /proxy/qaqdmin
> 
> 什么是 / 这是不对的?

Yes   /proxy/qaqdmin 的正确后端路由应该与之一样
