### ISSUE TITLE
pnpm i 安装依赖容易漏掉 peerDependencies

### ISSUE THREAD

**Issue by oozry12** [mx-space/kami#1570]
### Describe the bug

pnpm i 安装依赖，漏掉 peerDependencies
导致前端部署不成功。表现为有数据，但全部空白，完全没渲染出来页面。

### Reproduction

pnpm i

### System Info

```Shell
System:
    OS: Linux 5.10 Debian GNU/Linux 11 (bullseye) 11 (bullseye)
    CPU: (2) x64 AMD EPYC 7551 32-Core Processor
    Memory: 504.29 MB / 971.32 MB
    Container: Yes
    Shell: 5.1.4 - /bin/bash
  Binaries:
    Node: 18.14.0 - /usr/bin/node
    npm: 9.3.1 - /usr/bin/npm
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by oozry12** [comment]
可以加一个，再安装依赖
`pnpm config set auto-install-peers true`
`pnpm i`

**Comment by Innei** [comment]
kami 没有涉及 peerDependencies

**Comment by oozry12** [comment]
原来忘记强制`https` 现在前端成功了

**Comment by oozry12** [comment]
> kami 没有涉及 peerDependencies

有的。
部署文档 https://mx-space.js.org/deploy/index.html#%E9%83%A8%E7%BD%B2-kami
构建[#](https://mx-space.js.org/deploy/index.html#%E6%9E%84%E5%BB%BA)
这里选用 pnpm 作为包管理器。

bash
# 安装必需的模块
pnpm i
# 构建
pnpm build
