### ISSUE TITLE
网易云音乐的登录接口能否更改为二维码登录

### ISSUE THREAD

**Issue by sakurasep** [mx-space/kami#1610]
### Clear and concise description of the problem

kami现在的歌单功能因为网易限制手机登录现在无法使用，使用手机密码登录需要到网易云app中进行安全验证
![image](https://user-images.githubusercontent.com/70024132/223095558-36df1280-1723-4809-b3cb-566842e1ef4d.png)
![image](https://user-images.githubusercontent.com/70024132/223096307-d3185e59-5446-423d-b9f7-96a1cc6a2a58.png)

### Suggested solution

看到NeteaseCloudMusicApi提供的登录方法
![image](https://user-images.githubusercontent.com/70024132/223095863-691b4865-721a-4268-a6c3-195f15d3251a.png)
是不是可以让用户使用二维码登录，二维码图片用base64展示

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by Innei** [comment]
PR welcome

**Comment by zhijiwuyan** [comment]
you can have a try

**Comment by Innei** [comment]
Not Plan
