### ISSUE TITLE
拉取图片文件时无权限

### ISSUE THREAD

**Issue by matto49** [mx-space/kami#1640]
### Describe the bug

在执行git lfs fetch --all的时候报错了
fetch: 47 object(s) found, done.                                                                                                                                                                                                
fetch: Fetching all references...
batch response: Authorization error: https://github.1qi777.com/mx-space/kami.git/info/lfs/objects/batch                                                                                                                         
Check that you have proper access to the repository
error: failed to fetch some objects from 'https://github.1qi777.com/mx-space/kami.git/info/lfs'
![XSBL }_{6L_HU (X7EBN7VA](https://user-images.githubusercontent.com/54560462/230531497-0323cc86-f8b3-4933-8324-ee2ee51d5102.png)
![J}P%%JT{DU8KO~``JX8NZQP](https://user-images.githubusercontent.com/54560462/230531503-faf31a32-64c2-4fd1-bec5-26322a173b15.png)
试着输了一下https://github.1qi777.com/mx-space/kami.git/info/lfs/objects/batch，出现的是404

### Reproduction

git lfs fetch --all

### System Info

```Shell
![J}P%%JT{DU8KO~``JX8NZQP](https://user-images.githubusercontent.com/54560462/230531503-faf31a32-64c2-4fd1-bec5-26322a173b15.png)
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by ttimochan** [comment]
镜像站可能没有镜像 LFS 数据，你可以从 GitHub 拉取

**Comment by matto49** [comment]
第一次用git lfs...
输入git lfs ls-files，发现lfs追踪的文件都在public文件夹里
最后用ftp吧public文件夹上传了一下解决了
