### ISSUE TITLE
api设置有问题

### ISSUE THREAD

**Issue by yuano0** [mx-space/kami#1641]
操作系统： Ubuntu / 20.04 LTS amd64 (64bit) 
 Linux5.4.0版本。
面板版本: 3.28.2
系统版本：3.43.1
---
跟着https://mx-space.js.org/文档和【超可爱的前后端分离博客Mix-space搭建教程】b站教学视频一步一步做下来的。

然后安装好之后，api配置有问题，我是根据文档来的。
![1](https://user-images.githubusercontent.com/106160716/230629733-600f09c7-3674-4ec4-9768-3e09ec100693.png)
![2](https://user-images.githubusercontent.com/106160716/230629774-a08c89a0-230e-47ab-bc2c-7d5a5a1b63df.png)

打开前台这里会报错
![3](https://user-images.githubusercontent.com/106160716/230629842-2b581128-d529-4769-97ee-c7e7314d425f.png)

大佬求解，不知道哪一步出了问题，都是跟着文档走的。十分感谢。

**Comment by Innei** [comment]
不知道你这边反代是怎么配置的。

然后 module not found 的话，需要看下
<img width="1392" alt="image" src="https://user-images.githubusercontent.com/41265413/230635487-f7a63c49-2677-4918-8b4b-b146b0446c68.png">

**Comment by Innei** [comment]
我理解只要浏览器能访问 GitHub 就行了。反代的问题解决了吗
