### ISSUE TITLE
文本输入问题和版本更新

### ISSUE THREAD

**Issue by yuano0** [mx-space/kami#1653]
操作系统： Ubuntu / 20.04 LTS amd64 (64bit)
Linux5.4.0版本。
面板版本: 3.29.3
系统版本：3.43.3
---
输入框打字：我，直接自动转换成w。我记得以前是没这种情况的，难道是版本更新了吗...还是什么问题呀，这是视频。

https://user-images.githubusercontent.com/106160716/233369994-912b24f2-b895-4fed-b9e6-698961433aa2.mp4

2：版本号问题

![gengxin](https://user-images.githubusercontent.com/106160716/233370148-df855bbd-2d52-479c-b3a1-2f28d7133414.png)

我是根据这个进行更新的，然后更新好，也会重启kami和core。

然后我经常看innei大佬的博客，底部版本号是4.4.1，跟github更新刚好是一样的。
![inn](https://user-images.githubusercontent.com/106160716/233370586-52d58830-b37a-4aa2-a678-46d00f39c0c1.png)

我的是4.3.3
![yuano](https://user-images.githubusercontent.com/106160716/233370633-3429bece-8402-412c-a914-408a361a4a1b.png)

但是我每次都跟着更新呀，这难道有什么不一样的地方嘛...感谢大佬。

**Comment by Innei** [comment]
我这边没有复现呢。
