### ISSUE TITLE
json的使用

### ISSUE THREAD

**Issue by panancheng** [mx-space/kami#1660]
您好，我使用了很久的这个项目了。今天看到文档发现有json配置。

https://mx-space.js.org/use/kami-setting.html

这个跟kami的设置好像有点不太一样，查找了一会资料还是不太会配置这个。

请问，可以稍微教学演示一个配置参数吗，或者大概的讲一下思路，十分感谢！祝生活顺利！

**Comment by Innei** [comment]
每个标题都是一个配置的 key。

比如 `function.analyze.umami` 对应的 json 就是 


```json
{
  "function": {
    "analyze": {
      "umami": {
        
      }
    }
  }
}
```

YAML 就是 

```yaml
function: 
	analyze:
		umami: 
				
```


这部分的内容不知道如何编写能能加易懂。。

**Comment by panancheng** [comment]
> 每个标题都是一个配置的 key。
> 
> 比如 `function.analyze.umami` 对应的 json 就是
> 
> ```json
> {
>   "function": {
>     "analyze": {
>       "umami": {
>         
>       }
>     }
>   }
> }
> ```
> 
> YAML 就是
> 
> ```yaml
> function: 
> 	analyze:
> 		umami: 
> 				
> ```
> 
> 这部分的内容不知道如何编写能能加易懂。。

![Snipaste_2023-04-24_11-31-14](https://user-images.githubusercontent.com/131586989/233894171-e5fc6ba6-fc41-4cb7-a942-a7db2ae1970d.png)
大佬是这样吗..

**Comment by Innei** [comment]
<img width="739" alt="image" src="https://user-images.githubusercontent.com/41265413/234229761-397827d1-8c77-4d36-8370-06c18fe2c626.png">
