### ISSUE TITLE
mx-space文件夹无法删除

### ISSUE THREAD

**Issue by Rockney99** [mx-space/kami#1693]
![image](https://github.com/mx-space/kami/assets/42824224/759aaae9-32b2-4037-b711-4c05658c2612)
后台出现错误打算重装发现mx-space文件夹无法删除 删除了又会出现在目录里请问怎么解决

**Comment by miaoermua** [comment]
请关闭容器

**Comment by Rockney99** [comment]
![image](https://github.com/mx-space/kami/assets/42824224/08c8b4c6-b40a-4cd4-863a-ec5f4c57d3f1)
已经在宝塔删除了 实在不知道怎么弄了

**Comment by Rockney99** [comment]
![image](https://github.com/mx-space/kami/assets/42824224/8c7cc1e1-8670-47ab-9f27-cb40bf559066)

**Comment by Rockney99** [comment]
> 如果你有读写权限，直接删除即可

删不掉删了又会出现 ssh sudo rm -r mx-space 宝塔都试了删不掉

**Comment by ttimochan** [comment]
返回什么，请提供执行结果

**Comment by Rockney99** [comment]
rm -r没有返回信息

**Comment by ttimochan** [comment]
那就是执行成功了

**Comment by ttimochan** [comment]
无法复现
