### ISSUE TITLE
文章中的文章链接显示有误

### ISSUE THREAD

**Issue by licaoshun** [mx-space/kami#831]
我把程序按照文档步骤搭建好后，文章中的文章链接显示的不是我网站的地址，请问我该如何解决？谢谢。
![image](https://user-images.githubusercontent.com/33643780/130589368-d8e5645f-3d58-49ab-92e5-81bd39a30aa3.png)

**Comment by Innei** [comment]
![image](https://user-images.githubusercontent.com/41265413/130622704-0469307d-cae7-436e-8136-19e4c0a263f8.png)
