### ISSUE TITLE
CAUTION: request is not finished yet!

### ISSUE THREAD

**Issue by licaoshun** [mx-space/kami#857]
在请求图片API（/api/v1/uploads/image/xxx）时有极大几率出现长时间的pending，Stalled大约需要20秒到1分钟的时候才有响应。

![image](https://user-images.githubusercontent.com/33643780/132485221-910648f4-fcb6-4769-ae3f-c9e66c0484a0.png)

**Comment by licaoshun** [comment]
第一次打开图片地址时会秒开，然后刷新页面就会出现上述情况。

**Comment by Innei** [comment]
此接口在下个版本中已移除，暂时没有上传文件的必要
